name: CI

on:
  push:
    branches: ["main", "andre_dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Adding Repo
        uses: actions/checkout@v4
      - name: build command
        run: |
          dotnet build
  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: first step test
        run: |
          echo "Runing test"
          dir
  publish:
    runs-on: self-hosted
    needs: test
    steps:
      - name: first step pusblish
        run: echo "Runing pusblish"
  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
      - name: first step deploy
        run: echo "Runing deploy"
