name: CI

on:
  push:
    branches: ["main", "andre_dev"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  DOTNET_TOOLS_PATH: C:\Users\Lenovo\Desktop\tools-practice2

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Adding Repository
        uses: actions/checkout@v4
      - name: build command
        run: dotnet build
      - name: Check the repository files
        run: dir

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Check the repository files
        run: dir
      - name: Code inspection - Creating report
        run: |
          & "$env:DOTNET_TOOLS_PATH\jb.exe" inspectcode ./TrainProject.sln --o=./myApp/reports/report -f="xml"
      - name: Code inspection validation
        run: .\scripts\validate_report.ps1
      - name: Unit tests and code coverage
        run: |
          cd .\myApp.Tests\
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=reports/coverage
          cd ..
  publish:
    runs-on: self-hosted
    needs: test
    steps:
      - name: first step pusblish
        run: echo "Runing pusblish"
  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
      - name: first step deploy
        run: echo "Runing deploy"
