name: CI

on:
  push:
    branches: ["andreCarpio_p1_base"]
  pull_request:
    branches: ["andreCarpio_p1_base"]
  workflow_dispatch:

env:
  DOTNET_TOOLS_PATH: C:\Users\Lenovo\Desktop\tools-practice2

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Adding Repository
        uses: actions/checkout@v4
      - name: build command
        run: |
          dotnet build
          cd .\myApp\
          dotnet run
          cd ..

      - name: Check the repository files
        run: dir

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Check the repository files
        run: dir
      - name: Code inspection - Creating report
        run: |
          & "$env:DOTNET_TOOLS_PATH\jb.exe" inspectcode ./TrainProject.sln --o=./myApp/reports/report -f="xml"
      - name: Code inspection validation
        run: .\scripts\validate_report.ps1
      - name: Unit tests and code coverage
        run: |
          cd .\myApp.Tests\
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=cobertura -p:CoverletOutput=reports/coverage
          cd ..
      - name: Code Coverage validation
        run: .\scripts\validate_coverage.ps1
      - name: Unit tests report generation
        run: |
          cd .\myApp.Tests\
          & "$env:DOTNET_TOOLS_PATH\reportgenerator.exe" -reports:.\reports\coverage.cobertura.xml -targetdir:.\reports\coveragereport
          cd ..
      - name: Archive code coverage report - Donwload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: .\myApp.Tests\reports\coveragereport\
  publish:
    runs-on: self-hosted
    needs: test
    steps:
      - name: publich app
        run: |
          dotnet publish
          ./myApp/bin/Release/netcoreapp8/myApp
  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
      - name: first step deploy
        run: ./myApp/bin/Release/netcoreapp8/myApp
